WITH article_seed AS (
  SELECT *
  FROM (
    VALUES
      (
        1,
        'black-iron-weapon-intro',
        '雾铁初刃',
        'Mist-Iron First Blade',
        '名称：雾铁初刃。由雾镇旧矿的黑铁锻成，刃纹会记录每次提交与复盘。它没有耀眼光芒，却能把失败化成稳定力量，帮助新手斩开基础关卡，开启自己的段位传说。据说第一位通关者曾用它点亮第一盏雾灯。',
        'Mist-Iron First Blade: forged from Mist Town ore; marks turn failures into force and begin legend.',
        '/assets/art/ui/rewards/rank-weapons/thumbnails/black-iron-weapon-thumb.webp',
        '雾铁初刃黑铁兵器',
        'Mist-Iron First Blade weapon',
        'mist-town-wire',
        '雾镇通讯社',
        'Mist Town Wire'
      ),
      (
        2,
        'bronze-weapon-intro',
        '赤铜守誓刃',
        'Bronze Oath Blade',
        '名称：赤铜守誓刃。由雾镇训练场的铜钟碎片重铸，剑背能承受反复练习的震动。它会在通过第一批关卡时发热，提醒持有者守住基础，别让粗心偷走胜利。传说钟声响起时，勇气会回到手心，从此成为初阶勇者的信物。',
        'Bronze Oath Blade: reforged from training bells; it warms on first clears and guards basics.',
        '/assets/art/ui/rewards/rank-weapons/thumbnails/bronze-weapon-thumb.webp',
        '赤铜守誓刃青铜兵器',
        'Bronze Oath Blade weapon',
        'xingyin-desk',
        '星隐编辑部',
        'SPCG Desk'
      ),
      (
        3,
        'silver-weapon-intro',
        '银霜回响剑',
        'Silverfrost Echo',
        '名称：银霜回响剑。由排序冰原的霜银矿打磨，剑身会映出最近一次错误路径。它的力量不是快，而是让思路冷静回响，帮助学生在调试中找到真正的突破口。传说雪声会指出遗漏的条件，让答案浮出冰面。',
        'Silverfrost Echo: polished from frost silver; it mirrors wrong paths and sharpens debugging.',
        '/assets/art/ui/rewards/rank-weapons/thumbnails/silver-weapon-thumb.webp',
        '银霜回响剑白银兵器',
        'Silverfrost Echo weapon',
        'mist-town-wire',
        '雾镇通讯社',
        'Mist Town Wire'
      ),
      (
        4,
        'gold-weapon-intro',
        '金焰破晓剑',
        'Goldflame Dawn',
        '名称：金焰破晓剑。由火栈山谷的晨焰与金砂铸成，挥动时会点亮循环与分支的轨迹。它适合敢于冲榜的学生，把一次次稳定提交燃成破晓光芒。传说黎明前最亮的一剑来自它，照开新的赛道，从此不惧夜色。',
        'Goldflame Dawn: cast from valley fire and gold dust; it lights loops and steady submissions.',
        '/assets/art/ui/rewards/rank-weapons/thumbnails/gold-weapon-thumb.webp',
        '金焰破晓剑黄金兵器',
        'Goldflame Dawn weapon',
        'algorithm-herald',
        '算法先导报',
        'Algorithm Herald'
      ),
      (
        5,
        'platinum-weapon-intro',
        '铂星守衡刃',
        'Platinum Star Edge',
        '名称：铂星守衡刃。由星台铂片与平衡符文合成，刃心会校准速度和准确率。它提醒持有者别只追求快，也要让每个判断可靠，才能穿过更高段位的迷雾。传说失衡者握不住它，星光会悄然熄灭，从此稳住星心。',
        'Platinum Star Edge: alloyed with star plates; it balances speed, accuracy, and judgment well.',
        '/assets/art/ui/rewards/rank-weapons/thumbnails/platinum-weapon-thumb.webp',
        '铂星守衡刃铂金兵器',
        'Platinum Star Edge weapon',
        'xingyin-desk',
        '星隐编辑部',
        'SPCG Desk'
      ),
      (
        6,
        'diamond-weapon-intro',
        '钻晶裁云刃',
        'Diamond Cloud Cutter',
        '名称：钻晶裁云刃。由递归深渊的透明晶核切成，锋线能划开复杂问题的层次。它的威力在于分解，把庞大的任务拆成可攻克的小段，照亮进阶者的路径。传说云层会被它分成答案，露出隐藏阶梯，让高墙裂开。',
        'Diamond Cloud Cutter: cut from clear abyss crystal; it splits big problems into sharp steps.',
        '/assets/art/ui/rewards/rank-weapons/thumbnails/diamond-weapon-thumb.webp',
        '钻晶裁云刃钻石兵器',
        'Diamond Cloud Cutter weapon',
        'mist-town-wire',
        '雾镇通讯社',
        'Mist Town Wire'
      ),
      (
        7,
        'master-weapon-intro',
        '大师纹章剑',
        'Master Emblem Blade',
        '名称：大师纹章剑。由多次满分提交留下的光纹凝成，剑格刻着稳定、复盘和耐心。它不会替你思考，却会放大清晰的策略，让真正的高手在压力中保持节奏。传说纹章只回应沉着的人，并拒绝侥幸到底。',
        'Master Emblem Blade: born from perfect clears; it amplifies calm plans under pressure in duels.',
        '/assets/art/ui/rewards/rank-weapons/thumbnails/master-weapon-thumb.webp',
        '大师纹章剑大师兵器',
        'Master Emblem Blade weapon',
        'algorithm-herald',
        '算法先导报',
        'Algorithm Herald'
      ),
      (
        8,
        'grandmaster-weapon-intro',
        '宗师星轨刃',
        'Grandmaster Starpath',
        '名称：宗师星轨刃。由星轨碎片与旧算法图谱淬炼，挥出时会留下连续推理的光线。它属于能串起多种方法的挑战者，在复杂战斗中找到最短通路。传说星线会避开所有弯路，直抵终点，也照见最后答案。',
        'Grandmaster Starpath: tempered with star maps; it links methods into the shortest route in battle.',
        '/assets/art/ui/rewards/rank-weapons/thumbnails/grandmaster-weapon-thumb.webp',
        '宗师星轨刃宗师兵器',
        'Grandmaster Starpath weapon',
        'xingyin-desk',
        '星隐编辑部',
        'SPCG Desk'
      ),
      (
        9,
        'king-weapon-intro',
        '王者燎原剑',
        'King Wildfire Blade',
        '名称：王者燎原剑。由排行榜顶端的热焰与王冠钢锻成，出鞘时会点燃整片战场。它象征稳定统治力，只有能把基础、速度和判断合在一起的人才能驾驭。传说火光会让对手低头，也照见新的挑战，从此不退。',
        'King Wildfire Blade: forged from crown steel and rank fire; it rewards steady command in duels.',
        '/assets/art/ui/rewards/rank-weapons/thumbnails/king-weapon-thumb.webp',
        '王者燎原剑王者兵器',
        'King Wildfire Blade weapon',
        'mist-town-wire',
        '雾镇通讯社',
        'Mist Town Wire'
      ),
      (
        10,
        'legend-weapon-intro',
        '传奇长夜刃',
        'Legend Nightblade',
        '名称：传奇长夜刃。由长夜图书馆封存的暗银制成，刀锋会记住每场逆风翻盘。它的故事属于不放弃的人，在最难的题目前仍能保持思考，直到天光出现。传说它只在黎明前低鸣，召回勇气，直到破晓来临。',
        'Legend Nightblade: made from dark library silver; it remembers comebacks until dawn in long fights.',
        '/assets/art/ui/rewards/rank-weapons/thumbnails/legend-weapon-thumb.webp',
        '传奇长夜刃传奇兵器',
        'Legend Nightblade weapon',
        'algorithm-herald',
        '算法先导报',
        'Algorithm Herald'
      ),
      (
        11,
        'star-glory-weapon-intro',
        '星耀辉冠剑',
        'Star Glory Crown',
        '名称：星耀辉冠剑。由星耀徽章和流光冠冕融成，剑尖会召来无数细小星芒。它的威力来自持续积累，把每日练习变成光环，让持有者在赛场上被看见。传说星群会为坚持者让路，并照亮名字，直到名字发光。',
        'Star Glory Crown: fused from bright badges; daily practice becomes a visible aura on every arena.',
        '/assets/art/ui/rewards/rank-weapons/thumbnails/star-glory-weapon-thumb.webp',
        '星耀辉冠剑星耀兵器',
        'Star Glory Crown weapon',
        'xingyin-desk',
        '星隐编辑部',
        'SPCG Desk'
      ),
      (
        12,
        'server-weapon-intro',
        '云巅服战刃',
        'Server Apex Blade',
        '名称：云巅服战刃。由服务器核心与云端秘银锻造，刃面流动着全服挑战记录。它不是单人荣耀，而是连接所有对手的信号，提醒最强者仍要接受新的证明。传说它会同步每一次巅峰交锋，留下全服回响。',
        'Server Apex Blade: forged from core and cloud silver; it links all rivals and new trials now.',
        '/assets/art/ui/rewards/rank-weapons/thumbnails/server-weapon-thumb.webp',
        '云巅服战刃全服兵器',
        'Server Apex Blade weapon',
        'mist-town-wire',
        '雾镇通讯社',
        'Mist Town Wire'
      )
  ) AS rows(
    display_order,
    slug,
    topic_zh,
    topic_en,
    body_zh,
    body_en,
    image_url,
    image_alt_zh,
    image_alt_en,
    author_key,
    author_name_zh,
    author_name_en
  )
)
INSERT INTO today_news_articles (
  slug,
  status,
  topic_zh,
  topic_en,
  body_zh,
  body_en,
  image_url,
  image_alt_zh,
  image_alt_en,
  author_key,
  author_name_zh,
  author_name_en,
  published_at
)
SELECT
  slug,
  'published',
  topic_zh,
  topic_en,
  body_zh,
  body_en,
  image_url,
  image_alt_zh,
  image_alt_en,
  author_key,
  author_name_zh,
  author_name_en,
  NOW() - (display_order * INTERVAL '1 minute')
FROM article_seed
ON CONFLICT (slug) DO UPDATE
SET
  status = EXCLUDED.status,
  topic_zh = EXCLUDED.topic_zh,
  topic_en = EXCLUDED.topic_en,
  body_zh = EXCLUDED.body_zh,
  body_en = EXCLUDED.body_en,
  image_url = EXCLUDED.image_url,
  image_alt_zh = EXCLUDED.image_alt_zh,
  image_alt_en = EXCLUDED.image_alt_en,
  published_at = COALESCE(today_news_articles.published_at, EXCLUDED.published_at),
  updated_at = NOW();
