import type { UiLocale } from '@spcg/shared/types'

export type StudentUiMessages = typeof zhCnMessages

export const DEFAULT_UI_LOCALE: UiLocale = 'zh-CN'
export const UI_LOCALE_COOKIE = 'spcg_ui_locale'

export const SUPPORTED_UI_LOCALES: Array<{ value: UiLocale; label: string; nativeLabel: string }> = [
  { value: 'zh-CN', label: 'Chinese', nativeLabel: '中文' },
  { value: 'en-US', label: 'English', nativeLabel: 'English' },
]

const zhCnMessages = {
  common: {
    map: '地图',
    level: '关卡',
    leaderboard: '挑战榜',
    progress: '进度',
    settings: '设置',
    signOut: '退出登录',
    backToMap: '返回地图',
    close: '关闭',
    refresh: '刷新',
    save: '保存',
    loading: '加载中...',
    empty: '暂无数据',
    enter: '进入',
    page: '页',
  },
  auth: {
    signInTitle: '雾镇入口',
    signUpTitle: '创建角色',
    username: '用户名',
    email: '邮箱',
    signInIdentifier: '邮箱、用户名或昵称',
    password: '密码',
    confirmPassword: '确认密码',
    displayName: '昵称',
    avatarUrl: '头像链接（可选）',
    signIn: '登录',
    signUp: '注册新账号',
    start: '开始',
    backToSignIn: '返回登录',
    created: '账号已创建，请登录进入新手村。',
    forgotPassword: '忘记密码？',
    forgotPasswordTitle: '找回密码',
    forgotPasswordBody: '输入注册邮箱。如果账号存在，系统会发送一封密码重置邮件。',
    sendResetLink: '发送重置链接',
    passwordResetSent: '如果邮箱存在，重置链接已经发送，请检查邮箱。',
    resetPasswordTitle: '重置密码',
    resetPasswordBody: '设置一个新的登录密码，至少 8 位。',
    resetPassword: '重置密码',
    passwordResetDone: '密码已重置，请使用新密码登录。',
    resetTokenInvalid: '重置链接无效，请重新申请。',
    resetTokenExpired: '重置链接已过期，请重新申请。',
    requestNewResetLink: '重新申请重置链接',
  },
  settings: {
    eyebrow: '账号设置',
    title: '账号设置',
    tabProfile: '资料',
    tabLanguage: '界面语言',
    tabPhone: '手机号',
    tabParentBinding: '家长绑定',
    tabSecurity: '安全登录',
    profileTitle: '角色资料',
    profileBody: '修改地图和后台记录中显示的名称，并从本地选择头像图片上传。',
    displayName: '显示昵称',
    avatarFile: '本地头像',
    avatarHelp: '支持 PNG、JPG、GIF、WebP，服务端会压缩为 10KB 内 WebP 保存。',
    saveProfile: '保存资料',
    languageTitle: '界面语言',
    languageBody: '只切换按钮、导航、操作提示等界面文案；题目内容保持原文。',
    languageLabel: '操作界面语言',
    saveLanguage: '保存语言',
    phoneTitle: '手机号认证',
    phoneBody: '验证手机号后，用户名旁会显示认证标识。第一版使用开发验证码，不发送短信。',
    phoneNumber: '手机号',
    sendCode: '发送验证码',
    code: '验证码',
    verifyPhone: '验证手机号',
    parentBindingTitle: '家长绑定',
    parentBindingBody: '把完整家长邀请码提供给家长，用于家长账号绑定本学生。',
    studentId: '学生 ID',
    studentPhone: '学生手机号',
    parentInvite: '家长邀请码',
    inviteActive: '邀请码已生成',
    inviteBound: '已经绑定',
    inviteBoundBody: '已有家长通过邀请码绑定，该邀请码已自动失效。',
    inviteMissing: '暂无邀请码',
    inviteRevoked: '邀请码已失效',
    invitePreview: '完整邀请码',
    inviteUnavailable: '邀请码暂不可用。',
    askTeacherResetInvite: '请刷新页面或联系主老师重置邀请码。',
    boundParentCount: '已绑定家长',
    copyHint: '可复制完整邀请码给家长。',
    passwordTitle: '修改密码',
    passwordBody: '需要先输入当前密码，新密码至少 8 位。',
    currentPassword: '当前密码',
    nextPassword: '新密码',
    confirmPassword: '确认新密码',
    updatePassword: '更新密码',
    sessionTitle: '登录状态',
    sessionBody: '退出后会回到登录页。',
    signedIn: '已登录',
    phoneVerified: '手机号已认证',
    phoneUnbound: '未设置手机号',
    phonePending: '待认证',
    phoneUnboundShort: '未绑定',
    saved: '已保存。',
    profileFailed: '资料保存失败。',
    passwordFailed: '密码更新失败。',
    phoneFailed: '手机号验证失败。',
    languageFailed: '语言保存失败。',
  },
  map: {
    levelPrefix: '第',
    levelSuffix: '级',
    stageSuffix: '层',
    chapter: '级别',
    currentDirectory: '当前层目录',
    test: 'TEST',
    currentLevelAria: '当前关卡',
    completed: '已完成',
    current: '当前',
    unlocked: '可进入',
    locked: '未解锁',
    dailyTask: '今日任务',
    dailyTaskContinuePrefix: '复习后继续第',
    dailyTaskContinueSuffix: '层',
  },
  task: {
    goal: '目标',
    input: '输入',
    output: '输出',
    samples: '样例',
    expected: '期望输出',
    algorithmVideo: '算法视频',
    play: '播放',
    waiting: '等待',
    hints: '提示',
    solution: '题解',
    solutionLocked: 'AC 后解锁题解。',
    time: '时间',
    memory: '内存',
    sisterQuest: '关联题',
    difficulty: '难度系数',
    symbolNotes: '符号说明',
    noInput: '无输入',
    ready: '就绪',
    running: '运行中',
    expandTask: '放大题目阅读栏',
    shrinkTask: '缩小题目阅读栏',
  },
  ide: {
    editor: '编辑器',
    chooseLanguage: '选择编程语言',
    loadingEditor: '正在加载编辑器...',
    resetCode: '重置代码',
    restoreRunCode: '恢复上次运行代码',
    history: '提交记录',
    whiteboard: '逻辑画板',
    formatCode: '自动排版代码',
    expandEditor: '展开编辑器',
    collapseEditor: '收起编辑器',
    run: '运行',
    submit: '提交',
    judging: '判题中',
    analyze: 'AI 分析',
    analyzing: '分析中',
    analyzeAfterSubmit: 'Submit 后可分析',
    stdin: '标准输入',
    stdout: '标准输出',
    stdinPlaceholder: '输入运行数据',
    noInputPlaceholder: '本题无输入',
  },
  results: {
    judging: '判题中',
    title: '测试结果',
    notStarted: '未开始',
    ready: '就绪',
    submitWhenDone: '完成后提交。',
    cases: '测试点',
    message: '信息',
    failed: '失败',
    publicSample: '公开样例',
    publicSamples: '公开样例',
    testCase: '测试点',
    testCases: '测试点',
    running: '运行中...',
    queued: '排队中...',
    completed: '已完成',
    completedCount: '已完成',
    noResult: '暂无结果',
  },
  history: {
    title: '提交记录',
    label: '历史',
    status: '状态',
    owner: '提交人',
    submittedAt: '提交时间',
    source: '源码',
    loading: '加载中...',
    empty: '暂无提交记录',
    load: '载入',
    sourceAllowed: '源码',
    sourceLocked: '仅基础信息',
    me: '我',
    noResult: '暂无结果',
    cases: '个测试点',
  },
  feedback: {
    accepted: 'AC，通过啦',
    alreadyAccepted: '已 AC',
    backToMap: '回地图',
    continueNext: '继续下一题',
    challenge: '挑战：',
    goDo: '去做：',
    completeMastery: '本关完全掌握',
    goodMastery: '掌握良好',
    mainlineDone: '本关主线已完成',
    repairCompile: '先修编译错误',
    repairRuntime: '先定位运行错误',
    repairWrongAnswer: '先把这题修到 AC',
    repairWithHint: '用提示或画板定位',
    repairAskAnalysis: '建议请求分析',
  },
  profile: {
    eyebrow: 'Profile',
    title: '我的进度',
    coins: '金币',
    rank: '段位',
    garlic: '蒜粒',
    titleName: '称谓',
    weeklyKnowledge: '本周知识点',
    pendingRepair: '待修错题',
    attempted: '做过的题目',
    submissions: '提交记录',
    perPage: '每页',
    passed: '已通过',
    practicing: '练习中',
    code: '代码',
    problem: '题目',
    points: '分',
    pending: '排队中',
    judging: '判题中',
    assessmentSubmission: '考试提交',
    submissionDetail: '提交详情',
    sourceCode: '提交代码',
    judgeStatus: '判题状态',
    runtime: '运行时间',
    previousPage: '上一页',
    nextPage: '下一页',
    noAttempted: '还没有做过的题目。',
    noSubmissions: '还没有提交记录。',
    inventory: '背包装备',
    assessments: '段位赛历史',
    rewards: '奖励记录',
  },
  exam: {
    rankedMatch: 'SPCG 段位赛',
    restoring: '正在恢复本次考试进度...',
    start: '开始考试',
    startNew: '新开始一场考试',
    generating: '正在生成试卷...',
    realTimeJudge: '实时判题',
    realTimeNote: '考试中快速反馈；交卷后会重新跑满测试点并计算总分。',
    videoMonitor: '视频监控模式',
    videoMonitorBonus: '打开视频监控参加将会额外奖励 +5 金币',
    videoMonitorPrivacy: '仅打开本地摄像头实时显示，不录屏、不上传。',
    videoMonitorEnabled: '监考中',
    videoMonitorLocalOnly: '本地实时画面',
    videoMonitorExpand: '放大监控画面',
    videoMonitorCameraUnsupported: '当前浏览器不支持摄像头权限，请关闭视频监控模式后开始考试。',
    videoMonitorCameraDenied: '摄像头未授权，未创建监控考试。请允许摄像头，或关闭视频监控模式后开始。',
    questionList: '题目列表',
    paperQuestions: 'SPCG 段位赛题目',
    submitted: '已提交',
    unanswered: '未答题',
    finish: '交卷',
    scoring: '判题中...',
    confirmFinish: '确认交卷吗？交卷后本次段位赛会进入最终判题，不能继续修改代码。',
    scoreTitle: 'SPCG 段位赛成绩',
    refreshScore: '刷新成绩',
    refreshScoring: '刷新判题进度',
    noQuestions: '当前没有可用于段位赛的题目。',
    totalScore: '总分',
    fullScoreProblems: '满分题',
  },
  leaderboard: {
    title: 'SPCG 挑战榜',
    selectLevel: '选择等级',
    levelOverview: '当前等级概况',
    levelCoins: '本级当前积分',
    participants: '上榜学员',
    todayAc: '今日新增积分题',
    levelCount: '本级题目数',
    ranking: '挑战者排行',
    emptyTitle: '本级暂时还没有上榜学员',
    emptyBody: '获得本级题目、复习或段位赛积分后，会自动进入排行榜。',
    rank: '排名',
    student: '学员',
    levelCoin: '当前积分',
    passed: '题数',
    source: '来源',
    count: '题数',
    activity: '活跃状态',
    currentScore: '排行积分',
    firstAc: '首次 AC',
    rules: '积分规则',
    myRank: '我的排名',
    myProgress: '本级进度',
  },
  bug: {
    title: '提交 Bug 线索',
    close: '关闭 Bug 提交',
    placeholder: '请描述你发现的问题，例如：点了运行后没有输出，或某个按钮消失。',
    submit: '提交',
    submitting: '提交中',
    submitted: '已提交，感谢反馈。',
    failed: '提交失败，请稍后再试。',
  },
}

const enUsMessages: StudentUiMessages = {
  common: {
    map: 'Map',
    level: 'Levels',
    leaderboard: 'Leaderboard',
    progress: 'Progress',
    settings: 'Settings',
    signOut: 'Sign out',
    backToMap: 'Back to map',
    close: 'Close',
    refresh: 'Refresh',
    save: 'Save',
    loading: 'Loading...',
    empty: 'No data',
    enter: 'Enter',
    page: 'Page',
  },
  auth: {
    signInTitle: 'Mist Town Gate',
    signUpTitle: 'Create Character',
    username: 'Username',
    email: 'Email',
    signInIdentifier: 'Email, username, or nickname',
    password: 'Password',
    confirmPassword: 'Confirm password',
    displayName: 'Nickname',
    avatarUrl: 'Avatar URL (optional)',
    signIn: 'Sign in',
    signUp: 'Create account',
    start: 'Start',
    backToSignIn: 'Back to sign in',
    created: 'Account created. Sign in to enter the village.',
    forgotPassword: 'Forgot password?',
    forgotPasswordTitle: 'Reset Password',
    forgotPasswordBody: 'Enter your registered email. If the account exists, SPCG will send a reset link.',
    sendResetLink: 'Send reset link',
    passwordResetSent: 'If the email exists, a reset link has been sent. Please check your inbox.',
    resetPasswordTitle: 'Set New Password',
    resetPasswordBody: 'Choose a new password with at least 8 characters.',
    resetPassword: 'Reset password',
    passwordResetDone: 'Password reset. Sign in with your new password.',
    resetTokenInvalid: 'This reset link is invalid. Please request a new one.',
    resetTokenExpired: 'This reset link has expired. Please request a new one.',
    requestNewResetLink: 'Request a new reset link',
  },
  settings: {
    eyebrow: 'Account Settings',
    title: 'Account Settings',
    tabProfile: 'Profile',
    tabLanguage: 'Language',
    tabPhone: 'Phone',
    tabParentBinding: 'Parent Link',
    tabSecurity: 'Security',
    profileTitle: 'Profile',
    profileBody: 'Update the display name used on maps and records, and upload a local avatar image.',
    displayName: 'Display name',
    avatarFile: 'Local avatar',
    avatarHelp: 'PNG, JPG, GIF, and WebP are supported. The server saves it as WebP under 10KB.',
    saveProfile: 'Save profile',
    languageTitle: 'Interface language',
    languageBody: 'Only buttons, navigation, and operation tips change. Problem statements stay unchanged.',
    languageLabel: 'UI language',
    saveLanguage: 'Save language',
    phoneTitle: 'Phone Verification',
    phoneBody: 'After verification, a badge appears next to your username. v1 uses a development code, not SMS.',
    phoneNumber: 'Phone number',
    sendCode: 'Send code',
    code: 'Code',
    verifyPhone: 'Verify phone',
    parentBindingTitle: 'Parent Link',
    parentBindingBody: 'Share the full parent invite code with a parent account to link this student.',
    studentId: 'Student ID',
    studentPhone: 'Student phone',
    parentInvite: 'Parent invite',
    inviteActive: 'Invite created',
    inviteBound: 'Linked',
    inviteBoundBody: 'A parent has linked with this invite code, so the invite has been disabled automatically.',
    inviteMissing: 'No invite',
    inviteRevoked: 'Invite revoked',
    invitePreview: 'Full invite code',
    inviteUnavailable: 'Invite code is temporarily unavailable.',
    askTeacherResetInvite: 'Refresh the page or ask the primary teacher to reset it.',
    boundParentCount: 'Linked parents',
    copyHint: 'Copy the full invite code for the parent.',
    passwordTitle: 'Change Password',
    passwordBody: 'Enter your current password first. The new password must be at least 8 characters.',
    currentPassword: 'Current password',
    nextPassword: 'New password',
    confirmPassword: 'Confirm new password',
    updatePassword: 'Update password',
    sessionTitle: 'Session',
    sessionBody: 'Signing out returns you to the sign-in page.',
    signedIn: 'Signed in',
    phoneVerified: 'Phone verified',
    phoneUnbound: 'No phone number',
    phonePending: 'Pending',
    phoneUnboundShort: 'Unbound',
    saved: 'Saved.',
    profileFailed: 'Profile save failed.',
    passwordFailed: 'Password update failed.',
    phoneFailed: 'Phone verification failed.',
    languageFailed: 'Language save failed.',
  },
  map: {
    levelPrefix: 'Level ',
    levelSuffix: '',
    stageSuffix: '',
    chapter: 'Level',
    currentDirectory: 'Current stages',
    test: 'TEST',
    currentLevelAria: 'Current level',
    completed: 'Completed',
    current: 'Current',
    unlocked: 'Unlocked',
    locked: 'Locked',
    dailyTask: 'Daily task',
    dailyTaskContinuePrefix: 'Review, then continue level ',
    dailyTaskContinueSuffix: '',
  },
  task: {
    goal: 'Goal',
    input: 'Input',
    output: 'Output',
    samples: 'Samples',
    expected: 'Expected',
    algorithmVideo: 'Algorithm Video',
    play: 'Play',
    waiting: 'Waiting',
    hints: 'Hints',
    solution: 'Solution',
    solutionLocked: 'Solution unlocks after AC.',
    time: 'Time',
    memory: 'Memory',
    sisterQuest: 'Sister Quest',
    difficulty: 'Difficulty',
    symbolNotes: 'Symbol Notes',
    noInput: 'No input',
    ready: 'Ready',
    running: 'Running',
    expandTask: 'Expand statement',
    shrinkTask: 'Shrink statement',
  },
  ide: {
    editor: 'Editor',
    chooseLanguage: 'Choose language',
    loadingEditor: 'Loading editor...',
    resetCode: 'Reset code',
    restoreRunCode: 'Restore last run code',
    history: 'Submissions',
    whiteboard: 'Logic Whiteboard',
    formatCode: 'Format code',
    expandEditor: 'Expand editor',
    collapseEditor: 'Collapse editor',
    run: 'Run',
    submit: 'Submit',
    judging: 'Judging',
    analyze: 'AI Analysis',
    analyzing: 'Analyzing',
    analyzeAfterSubmit: 'Submit to analyze',
    stdin: 'stdin',
    stdout: 'stdout',
    stdinPlaceholder: 'Input data',
    noInputPlaceholder: 'No input for this problem',
  },
  results: {
    judging: 'Judging',
    title: 'Test Results',
    notStarted: 'Not started',
    ready: 'Ready',
    submitWhenDone: 'Submit when done.',
    cases: 'Cases',
    message: 'Message',
    failed: 'Failed',
    publicSample: 'Public Sample',
    publicSamples: 'Public Samples',
    testCase: 'Test Case',
    testCases: 'Test Cases',
    running: 'Running...',
    queued: 'Queued...',
    completed: 'Completed',
    completedCount: 'Completed',
    noResult: 'No result',
  },
  history: {
    title: 'Submissions',
    label: 'History',
    status: 'Status',
    owner: 'Owner',
    submittedAt: 'Submitted',
    source: 'Source',
    loading: 'Loading...',
    empty: 'No submissions yet',
    load: 'Load',
    sourceAllowed: 'Source',
    sourceLocked: 'Basic info only',
    me: 'Me',
    noResult: 'No result',
    cases: 'cases',
  },
  feedback: {
    accepted: 'AC, accepted',
    alreadyAccepted: 'Already AC',
    backToMap: 'Back to map',
    continueNext: 'Continue',
    challenge: 'Challenge: ',
    goDo: 'Go: ',
    completeMastery: 'Full mastery',
    goodMastery: 'Good mastery',
    mainlineDone: 'Main path complete',
    repairCompile: 'Fix compile error first',
    repairRuntime: 'Find the runtime error first',
    repairWrongAnswer: 'Fix this problem to AC first',
    repairWithHint: 'Use hints or whiteboard',
    repairAskAnalysis: 'Ask for analysis',
  },
  profile: {
    eyebrow: 'Profile',
    title: 'My Progress',
    coins: 'Coins',
    rank: 'Rank',
    garlic: 'Garlic',
    titleName: 'Title',
    weeklyKnowledge: 'Weekly Knowledge',
    pendingRepair: 'To Fix',
    attempted: 'Attempted Problems',
    submissions: 'Submissions',
    perPage: 'per page',
    passed: 'Problems',
    practicing: 'Practicing',
    code: 'Code',
    problem: 'Problem',
    points: 'pts',
    pending: 'Pending',
    judging: 'Judging',
    assessmentSubmission: 'Exam submission',
    submissionDetail: 'Submission Detail',
    sourceCode: 'Submitted Code',
    judgeStatus: 'Judge Status',
    runtime: 'Runtime',
    previousPage: 'Previous',
    nextPage: 'Next',
    noAttempted: 'No attempted problems yet.',
    noSubmissions: 'No submissions yet.',
    inventory: 'Inventory',
    assessments: 'Ranked Match History',
    rewards: 'Reward Ledger',
  },
  exam: {
    rankedMatch: 'SPCG Ranked Match',
    restoring: 'Restoring exam progress...',
    start: 'Start exam',
    startNew: 'Start a new exam',
    generating: 'Generating paper...',
    realTimeJudge: 'Real-time judging',
    realTimeNote: 'Fast feedback during the exam; final scoring reruns all test cases.',
    videoMonitor: 'Video monitor mode',
    videoMonitorBonus: 'Join with video monitor for an extra +5 coins',
    videoMonitorPrivacy: 'Local camera preview only. No recording or upload.',
    videoMonitorEnabled: 'Proctoring',
    videoMonitorLocalOnly: 'Local live preview',
    videoMonitorExpand: 'Expand monitor preview',
    videoMonitorCameraUnsupported: 'This browser does not support camera access. Turn off video monitor mode to start.',
    videoMonitorCameraDenied: 'Camera permission was not granted, so no monitored attempt was created. Allow camera access or turn off video monitor mode.',
    questionList: 'Question List',
    paperQuestions: 'SPCG Ranked Questions',
    submitted: 'Submitted',
    unanswered: 'Unanswered',
    finish: 'Finish',
    scoring: 'Scoring...',
    confirmFinish: 'Confirm finish? After finishing, final scoring starts and code can no longer be changed.',
    scoreTitle: 'SPCG Ranked Score',
    refreshScore: 'Refresh score',
    refreshScoring: 'Refresh scoring',
    noQuestions: 'No questions are available for this ranked match.',
    totalScore: 'Total score',
    fullScoreProblems: 'Full-score problems',
  },
  leaderboard: {
    title: 'SPCG Leaderboard',
    selectLevel: 'Select Level',
    levelOverview: 'Level Overview',
    levelCoins: 'Current Level Score',
    participants: 'Participants',
    todayAc: 'Today Scored Problems',
    levelCount: 'Problems',
    ranking: 'Challengers',
    emptyTitle: 'No students are ranked for this level yet',
    emptyBody: 'Earn problem, review, or ranked-match score in this level to join the leaderboard.',
    rank: 'Rank',
    student: 'Student',
    levelCoin: 'Current Score',
    passed: 'Passed',
    source: 'Source',
    count: 'Count',
    activity: 'Activity',
    currentScore: 'Rank Score',
    firstAc: 'First AC',
    rules: 'Rules',
    myRank: 'My Rank',
    myProgress: 'Level Progress',
  },
  bug: {
    title: 'Submit Bug Clue',
    close: 'Close bug form',
    placeholder: 'Describe the issue, for example: no output after Run, or a button disappeared.',
    submit: 'Submit',
    submitting: 'Submitting',
    submitted: 'Submitted. Thanks for the report.',
    failed: 'Submit failed. Please try again later.',
  },
}

export function normalizeUiLocale(value: unknown): UiLocale {
  return value === 'en-US' ? 'en-US' : DEFAULT_UI_LOCALE
}

export function getStudentUiMessages(locale: UiLocale): StudentUiMessages {
  return locale === 'en-US' ? enUsMessages : zhCnMessages
}
