JUDGE0_TELEMETRY_ENABLE=false
ENABLE_WAIT_RESULT=true
ENABLE_BATCHED_SUBMISSIONS=true
USE_DOCS_AS_HOMEPAGE=false

REDIS_HOST=judge0-redis
REDIS_PASSWORD=judge0-redis-password

POSTGRES_HOST=judge0-db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0-postgres-password

AUTHN_HEADER=
AUTHN_TOKEN=
AUTHZ_HEADER=
AUTHZ_TOKEN=

RAILS_ENV=production
SECRET_KEY_BASE=spcg-local-judge0-secret-key-base-change-in-production
